"""deleted category from Expense table

Revision ID: 3a072f9ea546
Revises: 867b2c71617e
Create Date: 2023-11-05 18:34:42.147467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a072f9ea546'
down_revision = '867b2c71617e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
