"""Added category_id in expense table

Revision ID: 502b76aa1441
Revises: 8ce85dd4a789
Create Date: 2023-11-05 13:59:28.415174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502b76aa1441'
down_revision = '8ce85dd4a789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_category_id', 'category', ['category_id'], ['id'])  # Named foreign key constraint
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_category_id', type_='foreignkey')  # Named foreign key constraint
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###

