"""returned to the first version

Revision ID: 6eb61bceb50a
Revises: ada2f3c11fc2
Create Date: 2023-11-05 15:02:58.374363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb61bceb50a'
down_revision = 'ada2f3c11fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('fk_category_id', type_='foreignkey')
        batch_op.drop_column('category_name')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.create_foreign_key('fk_category_id', 'category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###
