"""Added category_name in expense table

Revision ID: ada2f3c11fc2
Revises: 502b76aa1441
Create Date: 2023-11-05 14:31:44.257807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada2f3c11fc2'
down_revision = '502b76aa1441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
